04_Django/04_ORM/Online_Lab/ws/django_ws_4_b/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login')
]

04_Django/04_ORM/Online_Lab/ws/django_ws_4_b/todo_list_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
    path('accounts/', include('accounts.urls')),
]

04_Django/04_ORM/Online_Lab/ws/django_ws_4_b/todos/urls.py
from django.urls import path
from . import views


app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_todo/', views.create_todo, name='create_todo'),
    path('<work>/', views.detail, name='detail'),
]

04_Django/04_ORM/Online_Lab/ws/django_ws_4_b/accounts/models.py
from django.db import models

# Create your models here.

04_Django/04_ORM/Online_Lab/ws/django_ws_4_b/todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    work = models.CharField(max_length=100)
    content = models.TextField()
    is_completed = models.BooleanField()

04_Django/04_ORM/Online_Lab/ws/django_ws_4_b/accounts/views.py
from django.shortcuts import render

# Create your views here.
def login(request):
    return render(request, 'accounts/login.html')

04_Django/04_ORM/Online_Lab/ws/django_ws_4_b/todos/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    work = request.GET.get('work')
    context = {
        'work': work
    }
    return render(request, 'todos/index.html', context)

def create_todo(request):
    return render(request, 'todos/create_todo.html')

def detail(request, work):
    context = {
        'work': work
    }
    return render(request, 'todos/detail.html', context)

04_Django/04_ORM/Online_Lab/ws/django_ws_4_b/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>할 일 목록 관리 프로젝트</title>
</head>
<body>
  <a href="{% url "todos:index" %}">[MAIN]</a> | 
  <a href="{% url "todos:create_todo" %}">[CREATE]</a>
  <a href="{% url "accounts:login" %}">[LOGIN]</a>
  {% block content %}
  {% endblock content %}
</body>
</html>