05_DB/02_Many_to_one_relationship/02_Offline/Online_Lab/ws/db_ws_4_c/accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
]

05_DB/02_Many_to_one_relationship/02_Offline/Online_Lab/ws/db_ws_4_c/diaries/urls.py
from django.urls import path
from . import views


app_name = 'diaries'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:diary_pk>/comments/', views.comments_create, name='comments_create'),
    path('comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
]

05_DB/02_Many_to_one_relationship/02_Offline/Online_Lab/ws/db_ws_4_c/todo_list_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
    path('accounts/', include('accounts.urls')),
    path('diaries/', include('diaries.urls')),
    path('<int:user_pk>/password/', views.change_password, name='change_password'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

05_DB/02_Many_to_one_relationship/02_Offline/Online_Lab/ws/db_ws_4_c/todos/urls.py
from django.urls import path
from . import views


app_name = 'todos'

urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('mypage/', views.my_page, name='my_page'),
    path('<int:todo_pk>/', views.detail, name='detail'),
    path('<int:todo_pk>/delete/', views.delete, name='delete'),
    path('<int:todo_pk>/update/', views.update, name='update'),
]

05_DB/02_Many_to_one_relationship/02_Offline/Online_Lab/ws/db_ws_4_c/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>할 일 목록 관리 프로젝트</title>
  {% block style %}
  {% endblock style %}
</head>
<body>
  <a href="{% url "todos:index" %}"><img src="{% static "logo.png" %}" alt="logo" width="30px" height="30px;"></a> | 
  {% if request.user.is_authenticated %}
  <a href="{% url "todos:my_page" %}">[MY PAGE]</a>
  <a href="{% url "todos:create" %}">[CREATE]</a>
  <a href="{% url "diaries:index" %}">[DIARY]</a>
  <a href="{% url "accounts:update" %}">[USER_UPDATE]</a>
  
  <form action="{% url "accounts:logout" %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="[LOGOUT]">
  </form>

  <form action="{% url "accounts:delete" %}" method="POST">
      {% csrf_token %}
      <input type="submit" value="[SIGNOUT]">
    </form>
    <h3>Hello, {{ user.username }}</h3>
  {% else %}
    <a href="{% url "accounts:login" %}">[LOGIN]</a>
    <a href="{% url "accounts:signup" %}">[SIGNUP]</a>
  {% endif %}

  {% block content %}
  {% endblock content %}
</body>
</html>